jjwt:
    expiration: 18000 #seconds
    password:
        encoder:
            iteration: 33
            keylength: 256
            secret: mysecret
    secret: zaqWSXcdeRFVbgtYHNmjuikOlp0123456789#$*Ctel&gOwTh@mzaqWSXcdeRFVbg

logging:
    level:
      web: info
      com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
    file:
        name: logs/edgeserver.log
        path: logs
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}:%L - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}:%L - %msg%n'
server:
    error:
        whitelabel:
            enabled: false
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone:  ${EUREKA_URI:http://10.10.10.97:8761/eureka}
    instance:
        lease-renewal-interval-in-seconds: 30
        preferIpAddress: ${PREFERIPADDRESS:true}
   
spring:
    application:
        name: edgeserver
    kafka:
      bootstrap-servers: ${KAFKA_IP:http://10.10.10.98:9092}
    zipkin:
#       Server Url
        baseUrl: http://10.10.10.97:9411/
        discovery-client-enabled: true
        enabled: true
        service:             name: edgeserver        sender:          type: KAFKA
        kafka:          topic: zipkin
          
#   Percentage of logs export to zipkin server
    sleuth:
     sampler:
      probability: 0.5    

    datasource:
        driver-class-name: com.edb.Driver
        jdbc-url: ${JDBC_URL:jdbc:edb://10.10.10.94:5444/central_qc3}
        maximum-pool-size: ${POLL_SIZE:1}
        password: ${DB_PWD:enterprisedb123}
        testWhileIdle: true
        username: ${DB_USER:enterprisedb}
        validationQuery: SELECT 1

    jpa:
        properties:
            hibernate:
                format_sql: false
                show_sql: false
                use_sql_comments: false
    codec: 
      max-in-memory-size: 15MB   
    cloud:
      gateway:
        routes:
         - id: CEP-ADDCOUPONS-SERVICE
           uri: lb://cep
           predicates:
           - Method=POST
           - Path=/cep/addCoupons
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: CEP-GETCOUPONS-SERVICE
           uri: lb://cep
           predicates:
           - Method=GET
           - Path=/cep/getCoupons
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: ADDLOCALTIONDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/addLocaltionDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: ADDDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/d/addDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
           
         - id: ADDMONTHLYPRODUCTIONDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/d/addMonthlyProductionDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: ADDPRODUCTDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/addProductDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: ADDUSERDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/addUserDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: PRIMARYCOUPONS-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/getCoupons
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PRIMARYLABLES-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/getLables
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PALLETAVAILABILITY-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/palletAvailability
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PALLETCASEMAPPING-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/palletCaseMapping
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: VALIDATECASE-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/validateCase
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PRODSIZE-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=GET
           - Path=/v1/prodSize
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie 

         - id: STACKINGAVAILABILITY-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/stackingAvailability
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: SECONDARYPACK-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/secondaryPack
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PALLETSTORAGEMAPPING-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/palletStorageMapping
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PRODUCTIONPLAIN-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/productionPlain
           filters:
            - RemoveRequestHeader=Cookie
                      
         - id: COUPONSALLOCATELINE-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/couponsAllocateLine
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: LABELCODESALLOCATELINE-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/labelcodesAllocateLine
           filters:
            - RemoveRequestHeader=Cookie

         - id: HWEQUIPMENTS-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/hwEquipments
           filters:
            - RemoveRequestHeader=Cookie 
                     
         - id: INWARD-SERVICE
           uri: lb://shipment
           predicates:
           - Method=POST
           - Path=/v1/inward
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: OUTWARD-SERVICE
           uri: lb://shipment
           predicates:
           - Method=POST
           - Path=/v1/outward
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie  
            
         - id: DELIVERYNOTE-SERVICE
           uri: lb://shipment
           predicates:
           - Method=POST
           - Path=/v1/deliveryNote
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: DELIVERYNOTEDETAIL-SERVICE
           uri: lb://shipment
           predicates:
           - Method=POST
           - Path=/v1/deliveryNoteDetail
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: SHIPMENTMAP-SERVICE
           uri: lb://shipment
           predicates:
           - Method=POST
           - Path=/v1/shipmentMap
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
                   
         - id: COUPONINDENT-SERVICE
           uri: lb://cep
           predicates:
           - Method=POST
           - Path=/v1/couponIndent
           filters:
            - RemoveRequestHeader=Cookie
                        
         - id: PRODUCTIONDATA-SERVICE
           uri: lb://primary
           predicates:
           - Method=POST
           - Path=/v1/productionData
           filters:
            - RemoveRequestHeader=Cookie 

         - id: PALLETSCANNINGCOMPLETE-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/palletScanningComplete
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: SHIPMENTCOMPLETE-SERVICE
           uri: lb://shipment
           predicates:
           - Method=POST
           - Path=/v1/shipmentComplete
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
             
         - id: VERIFYDATA-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/verifyData
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: VERIFYDATADETAILS-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/verifyDataDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: SHORTAGECASEDETAILS-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/shortageCaseDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
                       
         - id: DAMAGE-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/damage
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: SHORTAGE-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/shortage
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
                        
         - id: REPACK-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/repack
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie 

         - id: REPACKCASEDETAILS-SERVICE
           uri: lb://secondary
           predicates:
           - Method=POST
           - Path=/v1/repackCaseDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: SHINWARD-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shInward
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie            

         - id: SH_OUTWARD-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shOutward
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie 
            
         - id: SHIPMENTNOTE-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shipmentNote
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie  
            
         - id: SHIPMENTNOTEDETAIL-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shipmentNoteDetail
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie             

         - id: SHCASEMAP-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shCaseMap
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie                         

         - id: SHCOMPLETE-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shComplete
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie  

         - id: CASESTORAGEMAPPING-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v1/caseStorageMapping
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: DN-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/addDNDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie            

         - id: TP-RECEIVING-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/tpReceiving
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: SHIPMENTOPTIONS-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/shipmentOptions
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie            

         - id: TOTALSHIPMENTCOMPLETE-SERVICE
           uri: lb://receiving
           predicates:
           - Method=POST
           - Path=/v1/totalShipmentComplete
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: CASESTORAGEMAPPING-V2-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v2/caseStorageMapping
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: PALLETSTORAGEMAPPING-V2-SERVICE
           uri: lb://tertiary
           predicates:
           - Method=POST
           - Path=/v2/palletStorageMapping
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: LABELTRAKING-SERVICE
           uri: lb://cep
           predicates:
           - Method=POST
           - Path=/v1/labelTraking
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: LINEDETAILS-SERVICE
           uri: lb://production
           predicates:
           - Method=POST
           - Path=/v1/lineDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie 
            
         - id: PAUSEORCOMPLETE-SERVICE
           uri: lb://production
           predicates:
           - Method=POST
           - Path=/v1/pauseOrComplete
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: DAILYPRODUCTION-SERVICE
           uri: lb://production
           predicates:
           - Method=POST
           - Path=/v1/dailyProduction
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie   
                                                                                                                                                         - id: PRODUCTION-SERVICE
           uri: lb://production
           predicates:
           - Method=POST
           - Path=/v1/production
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: ADDBATCHDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/addBatchDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie 

         - id: GETGRNDETAILS-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/getGrnDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: SAPDAILYPRODUCTION-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/sap/dailyProduction
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            
         - id: ADDINVOICE-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/addInvoice
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie

         - id: PRODMASTER-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/sap/addProductDetails
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/v1/sap/addProductDetails, /v1/test/v1_sap_addProductDetails      
          
         - id: BILLOFMATERIAL-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/productCoupon
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/v1/productCoupon, /v1/test/v1_productCoupon
         - id: DAILYGRN-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/sap/dailyProductionReceipt
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/v1/sap/dailyProductionReceipt, /v1/test/v1_sap_dailyProductionReceipt
 
         - id: PLANTCLOSING-SERVICE
           uri: lb://sap
           predicates:
           - Method=POST
           - Path=/v1/inventoryReconcilation
           - Header=Authorization, Bearer (.*)
           filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/v1/inventoryReconcilation, /v1/test/v1_inventoryReconcilation         
                                   
                       

      loadbalancer:        ribbon:          enabled: false
# AES Configuration         
AES:
    KEY: BPclh@mTt$Byel89
    IV: bpcl@123IntVec$1          